name: business
description: The business package.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  async_redux: ^25.4.0
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  dart_quill_delta: ^10.8.3
  fast_immutable_collections: ^11.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  http: ^1.5.0
  logging: ^1.3.0
  pb:
    path: ../pb
  pocketbase: ^0.23.0+1
  storage:
    path: ../storage

dev_dependencies:
  build_runner: ^2.10.1
  freezed: ^3.2.3
  pro_lints: ^5.0.0
