services:
  pocketbase:
    image: spectado/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - /path/to/data:/pb_data
      - /path/to/public:/pb_public
      - /path/to/migrations:/pb_migrations
    environment:
      PB_DEBUG: "true"