name: app
description: The progress-pal project.
publish_to: "none"
version: 0.1.0+12

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  async_redux: ^25.4.0
  business:
    path: ../business
  dart_quill_delta: ^10.8.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  go_router: ^16.3.0
  localization:
    path: ../localization
  pb:
    path: ../pb
  pro_pretty_logging: ^2.0.0
  pro_validator: ^2.0.1
  ui:
    path: ../ui
  window_manager: ^0.5.1

dev_dependencies:
  pro_lints: ^5.0.0

flutter:
  uses-material-design: true