name: pb
description: The pocketbase utils package.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  http: ^1.5.0
  pocketbase: ^0.23.0

dev_dependencies:
  pro_lints: ^5.0.0
