name: ui
description: The UI package.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  collection: ^1.19.1
  dart_quill_delta: ^10.8.3
  easy_date_timeline: ^2.0.9
  equatable: ^2.0.7
  extended_image: ^10.0.1
  fl_chart: ^1.1.1
  flex_color_scheme: ^8.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^11.5.0
  flutter_svg: ^2.2.1
  image: ^4.5.4
  image_picker: ^1.2.0
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  localization:
    path: ../localization
  lucide_icons_flutter: ^3.1.5
  mime: ^2.0.0
  package_info_plus: ^9.0.0
  theme_extensions_builder_annotation: ^6.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.10.1
  flutter_gen_runner: ^5.12.0
  pro_lints: ^5.0.0
  theme_extensions_builder: ^6.0.1

flutter_gen:
  output: lib/generated/
  colors:
    inputs:
      - assets/color/light.xml
      - assets/color/dark.xml
  integrations:
    flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  assets:
    - assets/logo/
    - assets/flags/
    - assets/equipments/
    - assets/muscle_groups/

